include: package:lints/recommended.yaml

# https://dart.dev/tools/analysis#the-analysis-options-file
analyzer:
  exclude: [build/**]
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

# https://dart.dev/tools/linter-rules
linter:
  rules:
    sort_pub_dependencies: true
