name: manifest
description: >-
  A command line tool to generate Dart package manifest from pubspec.yaml.
version: 1.0.0
homepage: https://github.com/treeinfra/manifest
environment: {sdk: ^3.4.3}

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
